"""Explicit user-scope launcher installation; never changes PATH, registry or startup.

Defaults to the retained legacy backend. Planning is read-only; --apply is required
for writes. Python 3.10+ runs this source installer. Only the legacy backend requires PowerShell.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = '.cucp-install.json'
FILES = {'legacy': ('cucp.cmd', 'cucp-launch.ps1'), 'core': ('cucp.cmd',), 'portable': ('cucp.cmd',)}
SCHEMA = 'cucp.user-launcher/v1'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def ps_literal(value):
    value = str(value)
    if any(c in value for c in ('\x00', '\r', '\n')):
        raise ValueError('Launcher paths cannot contain NUL or line breaks')
    return "'" + value.replace("'", "''") + "'"


def plan_install(root, bin_dir, *, backend='legacy', python_exe=None, portable_root=None):
    root, bin_dir = Path(root).resolve(), Path(bin_dir).absolute()
    if backend == 'legacy':
        command = [str(root / 'scripts/cucp.ps1')]
        health = ['powershell.exe', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', *command, '-Brief', 'macro', 'health-quick']
    elif backend == 'core':
        python_exe = Path(python_exe or sys.executable).resolve()
        if not python_exe.is_file():
            raise ValueError('Select an existing Python executable')
        command = [str(python_exe), str(root / 'pcucp-next/python/run_source.py')]
        health = [*command, 'doctor', '--json']
    elif backend == 'portable':
        if portable_root is None:
            raise ValueError('portable backend requires --portable-root; never guess a bundle')
        command = [str(Path(portable_root).resolve() / 'CUCP.exe')]
        health = [*command, 'doctor', '--json']
    else:
        raise ValueError('backend must be legacy, core or portable')
    entry = Path(command[-1])
    if not entry.is_file():
        raise ValueError(f'Backend entrypoint does not exist: {entry}')
    if backend == 'legacy':
        script = '# CUCP owned launcher; generated by install_runtime.py\r\n'
        script += '& ' + ' '.join(ps_literal(value) for value in command) + ' @args\r\nexit $LASTEXITCODE\r\n'
        cmd = '@echo off\r\nsetlocal DisableDelayedExpansion\r\nrem CUCP owned launcher; generated by install_runtime.py\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0cucp-launch.ps1" %*\r\n'
        contents = {'cucp.cmd': cmd.encode('ascii'), 'cucp-launch.ps1': script.encode('utf-8-sig')}
    else:
        def cmd_path(value):
            value = str(value)
            if any(c in value for c in ('"', '\x00', '\r', '\n')):
                raise ValueError('Invalid quoted batch path')
            return '"' + value.replace('%', '%%') + '"'
        # The only non-ASCII line follows chcp 65001, outside any parsed block.
        # Save/restore the console codepage and exit code. No PS dependency.
        cmd = ('@echo off\r\nsetlocal DisableDelayedExpansion\r\n'
               'rem CUCP owned launcher; generated by install_runtime.py\r\n'
               'for /f "tokens=2 delims=:" %%C in (\'chcp\') do set "_CUCP_CP=%%C"\r\n'
               'chcp 65001 >nul\r\n')
        if backend == 'core':
            cmd += 'set "CUCP_ROOT=' + str(root).replace('%', '%%') + '"\r\n'
        cmd += ' '.join(cmd_path(value) for value in command) + ' %*\r\n'
        cmd += 'set "_CUCP_EXIT=%errorlevel%"\r\nif defined _CUCP_CP chcp %_CUCP_CP% >nul\r\nexit /b %_CUCP_EXIT%\r\n'
        contents = {'cucp.cmd': cmd.encode('utf-8')}
    return {'schema': SCHEMA, 'backend': backend, 'root': str(root), 'bin_dir': str(bin_dir),
            'contents': contents, 'health_argv': health, 'authority': 'arguments forwarded unchanged; no implicit live control',
            'system_changes': [], 'requires': ['Windows'] + (['Windows PowerShell 5.1+'] if backend == 'legacy' else ['Python 3.10+'] if backend == 'core' else [])}


def manifest_for(plan):
    return {'schema': SCHEMA, 'backend': plan['backend'], 'root': plan['root'],
            'files': {name: digest(data) for name, data in plan['contents'].items()}}


def read_owned(bin_dir):
    path = bin_dir / MANIFEST
    if path.is_symlink():
        raise ValueError('Refusing symlinked ownership manifest')
    try:
        manifest = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError) as exc:
        raise ValueError('Existing launcher has no valid ownership manifest; preserve or move it manually') from exc
    if not isinstance(manifest, dict) or manifest.get('schema') != SCHEMA or not isinstance(manifest.get('backend'), str) or manifest.get('backend') not in FILES or not isinstance(manifest.get('files'), dict) or set(manifest['files']) != set(FILES[manifest['backend']]):
        raise ValueError('Invalid launcher ownership manifest')
    for name, expected in manifest['files'].items():
        path = bin_dir / name
        if path.is_symlink() or not path.is_file() or digest(path.read_bytes()) != expected:
            raise ValueError(f'Launcher was changed or is missing: {name}; no overwrite/delete performed')
    return manifest


def install(plan):
    """Write owned files atomically; refuse collisions; rollback ordinary write errors."""
    destination = Path(plan['bin_dir'])
    if destination.is_symlink():
        raise ValueError('Refusing a symlinked launcher directory')
    expected = FILES[plan['backend']]
    if set(plan['contents']) != set(expected):
        raise ValueError('Invalid installer artifact names')
    existing = any((destination / name).exists() or (destination / name).is_symlink() for name in ('cucp.cmd', 'cucp-launch.ps1', MANIFEST))
    if existing:
        previous = read_owned(destination)
        if previous['backend'] != plan['backend']:
            raise ValueError('Uninstall the owned launcher explicitly before changing backend')
    destination.mkdir(parents=True, exist_ok=True)
    contents = dict(plan['contents'])
    contents[MANIFEST] = (json.dumps(manifest_for(plan), indent=2, ensure_ascii=False) + '\n').encode('utf-8')
    old = {name: (destination / name).read_bytes() if (destination / name).exists() else None for name in contents}
    written, staged = [], {}
    try:
        for name, data in contents.items():
            with tempfile.NamedTemporaryFile(prefix='.cucp-stage-', dir=destination, delete=False) as stream:
                staged[name] = Path(stream.name)
                stream.write(data)
        # The public cmd entrypoint is last. Atomic replacement never follows a
        # swapped symlink; the previous known bytes are restored on ordinary errors.
        for name in [n for n in contents if n != 'cucp.cmd'] + ['cucp.cmd']:
            os.replace(staged[name], destination / name)
            written.append(name)
    except BaseException:
        for name in reversed(written):
            path = destination / name
            if old[name] is None:
                path.unlink(missing_ok=True)
            else:
                with tempfile.NamedTemporaryFile(prefix='.cucp-restore-', dir=destination, delete=False) as stream:
                    restore = Path(stream.name)
                    stream.write(old[name])
                os.replace(restore, path)
        raise
    finally:
        for path in staged.values():
            path.unlink(missing_ok=True)
    return manifest_for(plan)


def uninstall(bin_dir):
    """Remove only exact hash-verified generated files; never removes directory/PATH."""
    destination = Path(bin_dir).absolute()
    if destination.is_symlink():
        raise ValueError('Refusing a symlinked launcher directory')
    manifest = read_owned(destination)
    for name in (*FILES[manifest['backend']], MANIFEST):
        (destination / name).unlink()


def check_health(plan, *, run=subprocess.run):
    try:
        environment = dict(os.environ)
        if plan['backend'] == 'core':
            environment['CUCP_ROOT'] = plan['root']
        result = run(plan['health_argv'], env=environment, stdin=subprocess.DEVNULL, capture_output=True, text=True,
                     encoding='utf-8', errors='replace', timeout=30, check=False)
        if plan['backend'] == 'legacy':
            healthy = 'ok health' in result.stdout or 'passed=' in result.stdout
        else:
            healthy = result.returncode == 0 and json.loads(result.stdout).get('status') == 'ok'
        return healthy, 'health check passed' if healthy else 'health check did not confirm readiness'
    except (OSError, ValueError, subprocess.TimeoutExpired):
        return False, 'health check unavailable or timed out; inspect the selected backend'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--backend', choices=('legacy', 'core', 'portable'), default='legacy')
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--bin-dir', type=Path)
    parser.add_argument('--python-exe', type=Path)
    parser.add_argument('--portable-root', type=Path)
    parser.add_argument('--no-path-shim', action='store_true')
    parser.add_argument('--quiet', action='store_true')
    parser.add_argument('--apply', action='store_true', help='explicitly install the launcher or run requested health check')
    parser.add_argument('--uninstall', action='store_true', help='remove only hash-matching owned launcher files')
    args = parser.parse_args(argv)
    if sys.platform != 'win32':
        parser.error('Installation requires Windows; pure plan_install() is available for fixture tests')
    bin_dir = args.bin_dir
    if bin_dir is None:
        local = os.environ.get('LOCALAPPDATA')
        if not local:
            parser.error('LOCALAPPDATA is missing; specify --bin-dir')
        bin_dir = Path(local) / 'Microsoft/WindowsApps'
    try:
        if args.uninstall:
            if not args.apply:
                print('Would remove only hash-verified owned launcher files in ' + str(bin_dir))
                return 0
            uninstall(bin_dir)
            return 0
        plan = plan_install(args.root, bin_dir, backend=args.backend, python_exe=args.python_exe, portable_root=args.portable_root)
        if not args.apply:
            print(json.dumps({k: v for k, v in plan.items() if k != 'contents'}, ensure_ascii=False, indent=2))
            return 0
        if args.backend == 'legacy' and not shutil.which('powershell.exe'):
            raise ValueError('Windows PowerShell 5.1+ is required for the generated launcher')
        if not args.no_path_shim:
            install(plan)
        healthy, message = check_health(plan)
        if not args.quiet:
            print(f'Backend: {args.backend}; {message}')
            print('PATH, registry, startup and security settings were not changed')
            if not args.no_path_shim:
                print('Launcher: ' + str(bin_dir / 'cucp.cmd'))
                if str(bin_dir).casefold() not in [part.casefold() for part in os.environ.get('PATH', '').split(';')]:
                    print('Launcher directory is not on PATH; use its full path or add it yourself')
        return 0  # Original installer treats health warnings as nonfatal.
    except (OSError, ValueError) as exc:
        print('CUCP installer: ' + str(exc), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
